source "https://rubygems.org/"

# App Stack
gem "sinatra", "~> 1.4"
gem "sinatra-param", require: "sinatra/param"
gem "exchange_rates", :path => "../exchange_rates"

group :development do
  gem "rspec"
  gem "rake", "~> 10.0"
  gem "minitest", "~> 5.2"
  gem "rack-test", "~> 0.6"
end
